### PR TITLE
Fix to Issue #177: Tested, StructureView for grammars opens up without crashes

### PR DESCRIPTION
**Pull request by rojaster**
After update IDEA to 14.1 have some crashes with AbstractMethodError on TreeBasedStructureViewBuilder.createStructureViewModel() with ANTLRv4 plugin

Open a project with grammar g4 file and try to open a Structure:
AbstractMethodError: com.intellij.ide.structureView.TreeBasedStructureViewBuilder.createStructureViewModel(Lcom/intellij/openapi/editor/Editor;)Lcom/intellij/ide/structureView/StructureViewModel;

Fixed this thing with next lines of code for method, look at base anon class of TreeBasedStructureViewBuilder:
createStructureViewModel(@Nullable Editor editor)

Deleted my .gitignore and misc.xml file from commits

### CODE REVIEW

**Comment by parrt** [comment]
Hi. can you add yourself to https://github.com/antlr/intellij-plugin-v4/blob/master/contributors.txt ? thanks!

**Comment by rojaster** [comment]
Added;

**Comment by rojaster** [comment]
so sorry, my fault, i shouldn't close it

**Comment by rojaster** [comment]
on idea 14.0.2 plugin works great without some magic tricks, but after update to 14.1 my plugin crashes.

And that's what i found:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.jetbrains/intellij-idea/13.0.0/com/intellij/ide/structureView/TreeBasedStructureViewBuilder.java#TreeBasedStructureViewBuilder

Deprecated:
Use createStructureViewModel(Editor editor)
40
41  @NotNull
42  @Deprecated
43  public StructureViewModel More ...createStructureViewModel() {
44    throw new AbstractMethodError();
45  }


Recommended to use new version of this method. May be on 14.1 it was deleted.
on 13.x version will be all good , but for 12.x versions i don't find new implementations of this method.

**Comment by parrt** [comment]
Maybe I should create a final branch that works with 12 and then move on to a version that works in 13 and 14?

**Comment by rojaster** [comment]
Great solutions!

**Comment by parrt** [comment]
Ok, so your fix will work for 14.0.2 and 14.1?

**Comment by rojaster** [comment]
Yes, it is.

**Comment by parrt** [comment]
Ok, thanks. I'm racing to finish some stuff at work but I will incorporate your change shortly.

**Comment by parrt** [comment]
Hi.  I forgot you had a pull request and not just a bug report. I made the appropriate changes and close the bug. Perhaps for the future, you can send a new pull request with just your addition to the contributors.txt?

**Comment by rojaster** [comment]
I'm added to contributors.txt myself

**Comment by parrt** [comment]
Any idea how I can cherrypick from a pull request? Failing that can you send another pull with just your contrib addtion?

**Comment by rojaster** [comment]
I can't understand how my last commit was not included at pull request

**Comment by parrt** [comment]
Sorry for confusion. I fixed the bug as reported w/o seeing/remembering the pull so, for future, wanted separate commit for your contribution.

**Comment by rojaster** [comment]
i sent new pull request, just add only contributors.txt
okay) thanx)

**Comment by parrt** [comment]
ok, figured out cherrypick. done.
Ter

**Pull request closed without merging**
