### PR TITLE
Add support for brace matching

### PR DESCRIPTION
**Pull request by testn**
This will allow the brace matching feature in intellij

### CODE REVIEW

**Comment by testn** [comment]
ping @parrt

**Comment by parrt** [comment]
interesting. I will take a look the next time I update the plug-in. Thanks

**Comment by bjansen** [comment]
@testn could you rebase your PR please?

**Comment by parrt** [comment]
Can you sign https://github.com/antlr/intellij-plugin-v4/blob/master/contributors.txt ?

**Comment by bjansen** [comment]
Superseded by https://github.com/antlr/intellij-plugin-v4/commit/051d6226e866a4f3c6cd32d5d11b213f1f8dfd37

**Pull request closed without merging**
