### PR TITLE
replaced backgroundcolor with colored border

### PR DESCRIPTION
**Pull request by nopeslide**
`JBColor.White` is theme dependent, therefore not visible in Darcula theme.
Mitigated this problem by drawing a green border.

### CODE REVIEW

**Comment by bjansen** [comment]
According to the readme:
> The darkened background node is the node for the rule containing the decision that is ambiguous.

I think it would make sense to keep this statement true in Darcula mode, i.e. the right side should be darker than the left side. We could use the editor's background color for example:

```java
if ( i==highlightTreeIndex ) {
	wrapper.setBackground(JBColor.white);
} else if ( UIUtil.isUnderDarcula() ) {
	wrapper.setBackground(Gray._43);
}
```

WDYT?

**Comment by bjansen** [comment]
Also, don't forget to add your name to [contributors.txt](https://github.com/antlr/intellij-plugin-v4/blob/master/contributors.txt).

**Comment by nopeslide** [comment]
Even better, since green usually implies something as correct.

**Comment by bjansen** [comment]
Thanks for your contribution!

**Pull request merged**
