### PR TITLE
[WIP] Parse and tree view refresh in background

### LINKED ISSUE #546: UI freeze after parse on SQL grammars with large inputs
I'm trying to profile my SQL grammar on a large input with diverse statements, which used to go fine in previous versions some years ago.
I managed to consistently reproduce a UI freeze that seems to happen *after* parsing of the input is finished.
Looking at the CPU load, there's a ~15s multithreaded parser spike and then a single thread becomes pinned at 100% and UI freezes.
Considering this and #381 it seems that the issue is with displaying parsing/profiling results. And it happens even when disabling every option on the left of the preview panel (auto-update, parse-tree etc).

Repro:
Use [example PostgreSQL grammar](https://github.com/antlr/grammars-v4/tree/master/sql/postgresql) or [my PostgreSQL grammar](https://github.com/pgcodekeeper/pgcodekeeper/blob/master/apgdiff/antlr-src/SQLParser.g4).
Test `root` rule (`sql` rule in my grammar).
Concat every [example SQL](https://github.com/antlr/grammars-v4/tree/master/sql/postgresql/examples) into a single file, i used this command: `find *.sql | xargs -I{} sh -c "cat {}; echo ''" > _concat.sql`.
Use the new, ~2.9MB file as ANTLR Preview input.
Note UI freeze after a short delay (parse stage). UI doesn't unfreeze for at least 10 minutes, process has to be killed.

### PR DESCRIPTION
**Pull request by parrt**
Fixes #546.  Parsing / tree view is now updated with a queue that doesn't update parse tree in GUI thread nor on each key stroke.  @bjansen can you take a peek? In the end was simple to add.

### CODE REVIEW

**Comment by bjansen** [comment]
So, say we have a grammar that takes 5s to parse a simple input. If i type 3 characters in the editor, the UI won't freeze, but what's submitted in the queue for the 1st char won't be cancelled when the second char is typed, right? The preview will be refreshed 5s, 10s and 15s after the characters are typed?

**Review by bjansen — APPROVED** [review]

**Comment by bjansen** [comment]
Wait no, IIUC you're using `this` as the identity of `Update` instances

From the Javadoc of `Update`:
> Equal tasks (instances with the equal identity objects) are merged, i.e. only the first of them is executed.

So if you type 3 consecutive characters, only the first update will be run and the two others will be discarded. I think this will result in the wrong results for grammars that take more than a few ms to process the input?

For simple grammars that run fast, I think it works fine because what is submitted to the queue runs faster than the delay between each character typed in the input.

**Comment by parrt** [comment]
Yeah, I worked all afternoon yesterday and learned more. I think we have a general problem here.  As you mentioned, I hadn't figured out how to deal with canceling previous purses and starting the new one. It seems like all it does is throw out new ones that come in, which seems odd.

Also I realized that the queue does not run them on separate thread; it uses the GUI thread so I had to launch them separately and then use invokeLater so it calls `repaint()` on the GUI thread. It works!  The GUI is responsive during all of our work but as you'll see next I think we are defeated by the size:

Next, I realize that there's no way to take a tree with 1.5 million nodes and draw that with swing. What I've noticed is that it finishes the layout and drawing of the tree, according to a few print statements. Very quickly but shortly there after it freezes because I think drawing only queues up actions in swing and then later the gooey thread hasta actually draw those rectangles etc...  I heard from unexperienced plug-in guy that there's no way even the hierarchy view is going to handle 1.5 million entries.

I'm not sure why someone wants to pull in that much code for parsing anyway. My suggestion is that we figure out what's the development env will handle and then set a threshold to govern sizes.

**Comment by parrt** [comment]
@bjansen So I got the profile are running although I'm not sure I am interpreting everything correctly so I'm including some snapshots here. When I asked her to parse 5000 lines of SQL, it appeared to complete the layout the tree but then it started spinning ball and froze for 20 seconds. The profiler says that the AWT thread was going nuts and nothing was being touched in the GUI by my Mouse or text. Highlighted section shows where I think it froze:

Screen Shot 2022-05-08 at 10 59 49 AM

It sure looks to me from these method lists that it was just sitting there trying to draw something:

Screen Shot 2022-05-08 at 10 59 23 AM

Screen Shot 2022-05-08 at 11 01 15 AM

**Comment by parrt** [comment]
Ok, I have confirmed that not even the simple treeview from a main program works. The GUI immediately freezes after I tried to draw:

```
$ grun SQL sql -gui < /tmp/all.sql 
```

That is with 76k lines. It seems to work "OK" with 5000 lines of sql.

Anyway, I just don't think the GUI freezing is our problem.  Displaying millions of no it's just not some thing that swing with set up for.

**Comment by bjansen** [comment]
> Displaying millions of no it's just not some thing that swing with set up for.

Right, that was what I was worrying about in https://github.com/antlr/intellij-plugin-v4/issues/546#issuecomment-1110933290. Even if we can parse input without freezing the IDE, I don't think we can reasonably expect Swing to render that much nodes. Memory usage will also be catastrophic.

My opinion is that the preview window is supposed to help people _debug_ their grammar, not do performance tests on large inputs (although 5000 lines is not *that* large). I'm wondering if it's worth investing so much time trying to optimize the plugin for such "edge cases".

**Comment by bjansen** [comment]
Maybe we can add a hard limit to render the first N nodes and discard the rest?

**Comment by parrt** [comment]
good advice. yes, i'll think about a simple limit or simply turn off the view if it's bigger than some threshold

**Comment by parrt** [comment]
Closed in favor of https://github.com/antlr/intellij-plugin-v4/pull/551

**Pull request closed without merging**
