### PR TITLE
Fixes #559: Bug closing non-active grammar file

### LINKED ISSUE #559: Bug closing non-active grammar file
Open two grammars T1.g4 and T2.g4.  Show T1.g4 but click close box on T2.g4 which closes the T1.g4 preview pane and when you reopen, it's dehighlighted and inactive.

Screen Shot 2022-05-21 at 2 09 09 PM

Must close/open grammar to get correct preview.

Screen Shot 2022-05-21 at 2 10 18 PM

Gotta be a weird thing like *killing the wrong previewState based upon active window not the one being closed*.

### PR DESCRIPTION
**Pull request by kjarrio**
Signed-off-by: Kjartan Olason <olasonk@gmail.com>

@@ -1,5 +1,23 @@

### CODE REVIEW

**Comment by parrt** [comment]
Wow! Thanks, @kjarrio ! I'll check it out soon.

**Comment by kjarrio** [comment]
I'm unsure why the build failed, I tried to replicate it here with same parameters, but hope the latest commit will fix it.

**Comment by parrt** [comment]
Looks like there are still some issues with mocking.

**Comment by parrt** [comment]
Looks like:

```
/home/runner/work/intellij-plugin-v4/intellij-plugin-v4/src/test/java/org/antlr/intellij/plugin/editor/Issue559Test.java:51: error: package ToolWindowHeadlessManagerImpl does not exist
        return new ToolWindowHeadlessManagerImpl.MockToolWindow(getProject()) {
                                                ^
/home/runner/work/intellij-plugin-v4/intellij-plugin-v4/src/test/java/org/antlr/intellij/plugin/editor/Issue559Test.java:55: error: method does not override or implement a method from a supertype
            @Override
            ^
```

**Comment by kjarrio** [comment]
Just removed those, I am going to have a better look on how to trigger these errors on my local env

**Comment by kjarrio** [comment]
yeah, there is an issue with the MockToolWindow, it is probably only available in some different version of IDEA... will figure out a different way to test this

**Comment by kjarrio** [comment]
Apparently the MockToolWindow isn't available but I created one

**Comment by parrt** [comment]
thanks, @kjarrio !

**Comment by parrt** [comment]
Unfortunately, I have to back this out. The initComponents() function somehow freezes entire IDE with 2022.3 release. :( sorry!

**Pull request merged**
