### PR TITLE
Dev. Migration to gradle project

### PR DESCRIPTION
**Pull request by brizjin**
Hello!
I did migrate project to a gradle project. And also change folders structure to gradle default folder organization. With gradle project it will be more easy to grow this project. Like testing plugin with different version of Idea just by changing Idea version in gradle.build file. Also antlr-complite can be add as a dependence to gradle build (but needs to be add to maven repos first). Also calling bild.py for generation can be done as part of gradle building process.

### CODE REVIEW

**Comment by parrt** [comment]
howdy. i don't know gradle I'm afraid though!  kind of a massive change.

**Comment by brizjin** [comment]
Moved branch to head of master. Now it do not change files structure. Only nessasary changes.

- .idea/gradle.xml, gradle/wrapper/*, gradlew, gradlew.bat are all autogenerated.
- .idea/misc.xml, .idea/modules.xml, intellij-plugin-v4.iml will autogenerate on gradle sync stage or gradle project import stage and removed only from git index
- lib/* deleted because now it as gradle dependency in maven repo, will automatically download by gradle build task
- META-INF/plugin.xml moved to resources/META-INF/plugin.xlm, this is restriction on build
- bild.py removed, it replaced by generateANTLR task
- now all project structure exists in build.gradle, where source directoris are, were all recources. Which dependencies need to be downloaded before build. Also generateANTLR task do the same as bild.py did before. It autoruns before compileJava task. Now to start project from scratch enought run runIde task and do not needs to run generateANTLR before, it will runs in first step.

**Comment by parrt** [comment]
Hi. I will take a look after I get 4.7.1 antlr out the door.

**Comment by gejun123456** [comment]
I hope this can be merged soon, there are lots of advantage to use gradle to build the project.
mainly help people to set up the environment quicker and could test code on different IDE version.
For the pull request I think you should add   **updateSinceUntilBuild false**  to the intellij part in build.gradle.

**Comment by parrt** [comment]
Ok, can you give me instructions on how to build? I've never touched gradle.

**Comment by gejun123456** [comment]
here is a tutorial about using gradle
https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html
reimport the plugin project with gradle
then add a gradle task configuration for the project as in the tutorial 


The tutorial task runIdea need to be replaced with using runIde instead from 
https://github.com/JetBrains/gradle-intellij-plugin/blob/master/README.md

We should do the PR instead of the commit

**Comment by parrt** [comment]
ok, can you sign https://github.com/antlr/intellij-plugin-v4/blob/master/contributors.txt ?

**Comment by parrt** [comment]
oh thanks but can you edit that file with that info as part of this PR? thanks!

**Comment by gejun123456** [comment]
@brizjin  can you help to edit the contributors file? thanks!

**Comment by brizjin** [comment]
did update contributors file and squash all changes to one commit

**Comment by parrt** [comment]
thanks!

**Pull request merged**
