### PR TITLE
Resolve imports

### PR DESCRIPTION
**Pull request by roggenbrot**
Resolve imports located in custom `libFolder` #383

### CODE REVIEW

**Comment by roggenbrot** [comment]
@bjansen Are the failed builds related to current master version or a CI problem? Can't reproduce this problems locally

**Comment by bjansen** [comment]
HI @roggenbrot, and thanks for your contribution! I think the problem comes from Travis, everything works fine on GitHub Actions and my machine.

**Comment by bjansen** [comment]
LGTM, but could you add your name to `contributors.txt` please?

**Comment by roggenbrot** [comment]
Done

**Pull request merged**
