### PR TITLE
Add rule name to Simple/Expert Profiler Grid, optional build of tree/hierarchy

### PR DESCRIPTION
**Pull request by OleksiiKovalov**
**What does this PR do?**
1. Adds rule name to "Simple Profiler Grid" and "Expert Profiler Grid"
2. timeInPrediction  column converted back to "long, in ms"
3. Added toggle action to turn on/off building of tree/hierarchy after parse

**Why?**
1. it is more clear & convenient to see the rule name (which corresponds to grammar non-literal rule) than numeric decision number.
2. Sorting on long column works in the right way, as opposed to sorting "number as string", when "10" comes right after "1"
3. Building a tree/hierarchy for big test scripts can take a bunch of time, so it is good to have an option to turn it off.

**How is it checked?**
1. Unit tests for plugin project still run OK
2. manually tested by parsing and viewing several scripts for real oracle grammar.

**Risk analysis**
This change isn't particularly risky. All existing tests still pass, and even if something were to go wrong, it would have a negligible impact on the plugin as a whole.

### CODE REVIEW

**Comment by OleksiiKovalov** [comment]
@bjansen

**Comment by bjansen** [comment]
You can leave `IC-2019.1.3` and still use the plugin in 2021.x, it will work.

**Comment by OleksiiKovalov** [comment]
hi @bjansen , please note - new features added to PR

**Comment by bjansen** [comment]
@OleksiiKovalov why do you need to disable automatic updates to the tree viewer and hierarchy viewer? Also, could you please avoid mixing separate features in the same PR?

**Comment by OleksiiKovalov** [comment]
@bjansen 
1. when profiling slow grammar with big/complex test script it takes several seconds to parse/profile/show profiler data - and 1-2 minute to build/show tree and hierarchy
so I've decided that it would be great to gave an option to turn automatic updates off - having it "On" by default.
2. Sorry. Should I divide changes into 2 PRs?

**Comment by bjansen** [comment]
OK I understand why you added the buttons.

There's two more changes you should do before the PR is ready:
* modify the tooltip of the `Time` column, because the value is now expressed in µs and not in ms
* add your name to `contributors.txt`

**Comment by bjansen** [comment]
Thanks for your work!

**Pull request merged**
