### PR TITLE
Add rule highlighting, group actions, and test parser rule intention

### PR DESCRIPTION
**Pull request by ze**
Changes made:
* Allow for the action allowing you to test a parser rule to also be used as an intention (triggered by alt+enter). No need for a mouse anymore. 
image
* Group the ANTLR actions 
image
 into a group to de-clutter the UI. The actions do not show up when selecting files that aren't g4 files. Furthermore, fixed the bug that caused the ANTLR actions to not show up in the tool menu. The code was there, but it was pointing to a section in the tools tab that no longer existed.
* Moved the Icon class to the icons package to allow IntelliJ to use them in resource files. This can be foregone in IJ version 2022.*, but the plugin supports 2018 as a minimum. As a result, it needs to be in the icon package. It sadly creates the import statement `import icons.Icons`, but it is a poison we have to consume to use this feature (probably why 2022.* has this change)
* Bump the ANTLR version to 4.9.3. Nice free change
* I think this is the key change, but clicking a parser rule/lexer token with your mouse no longer selects it physically. It instead creates a highlighted area (similar to how the IDE highlights). This allows you to type after selecting a node. I often had the problem where I would click the edge of a rule to add something, have it be selected, and in my hurry to write something, delete the entire block. Often times, this is the entire program I wrote in the text field or a large scoped block. 
image

Some things I noticed + made the choice to do:
* Whenever I entered a function, I would reformat it with IntelliJ's reformatter. It made the most sense to me.
* I reformatted the plugin.xml file + added an ignore statement to suppress the complaint that the v in `ANTLR v4` is lowercase. This made it easier for me to work with. I think it's more readable this way.
* The intention needs a before/after template file. It will cause an IDE error otherwise, so I added an empty description. IIRC, this requirement is possible to disappear in future versions of the ide.
* I discovered a bug with the preview tab. Highlight a parser rule, click away, then type a single letter. The original area will re-highlight for the first time, then not the second time. This error was present before my changes and I considered the possibility that fixing the error would make the PR larger than it already is. I plan on adding more changes since I use this plugin fairly often in work/personal. I identified the RCA as being key events triggering a refresh in the hierarchy tree, which caused the listeners attached to the tree to re-ping. One way would be to do-away with the listeners. I'm still thinking of it.
* I added a quick and small class called `PossiblyEmptyTreeTextProvider` due to the bug (fairly long lived-bug) where the parse tree graph, when supposed to be given a string list of rule names, is instead given an empty list. Fixing this as well would make the PR larger, so I made a stop-gap measure to do away with the bug by giving `N/A` as a response, which should be promptly fixed by the code itself. `ApplicationManager.getApplication().invokeLater` is the string to search for in `PreviewPanel` to understand why.

I've tested the plugin on 2018.3, 2019.1, and 2021.3 with no problems.

### CODE REVIEW

**Comment by bjansen** [comment]
Thanks for your contribution! Just a side note: it would have been easier to review the changes if they had been split into multiple PRs. This way changes would have been categorized, and it would have been easier to accept or reject them individually. I'm not saying I'm going to reject your work, but you know what I mean 😉.

I'll probably start reviewing tomorrow.

**Comment by ze** [comment]
I wasn't sure if it was okay to put up multiple PR's, but for the future, I'll definitely just do that instead of making one with 26 files changed. Especially since the repository has seen some changes made that may have invalidated some of the ones I made on my end. I can break up the PR if you want, every individual commit can pretty much be their own PR (and it's easy to do with a cherry pick!) Thank you!

**Comment by parrt** [comment]
hi @ze I've made some changes myself, specifically around what happens inside the input window. I think we need to split this apart. Perhaps you could split it into a PR per feature you mentioned, although I'm now happy with the way it handles the input window so I'm not sure about that one.

Regarding the icon stuff. I'm now requiring or at least assuming only 2020.2.1 or above. Well that get rid of some of the poison?

**Comment by ze** [comment]
Alright, that sounds good to me! I'll close this PR, rebase my branch and submit individual PR's for what hasn't already been dealt with in commits made by others that fixed some issues here and there. I'm fairly busy with work, but I'll get to this at some point ideally in the next week or two. Thank you for the feedback!

**Pull request closed without merging**
