### PR TITLE
folding improvements

### PR DESCRIPTION
**Pull request by jasonnn**
here is a short summary...
* traversal of grammars for folding is more directed and should be more efficient
* when a bunch of rules are on adjacent lines they get folded together
*added a folding test
* ast/psi iterables in the style of [google's FluentIterable](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/FluentIterable.html)

### CODE REVIEW

**Comment by parrt** [comment]
Hi.  I'm wondering if we should hold off on this until we can investigate using the standard antlr trees. Then we can use all of the XPath and other tree/token support built-in.

**Comment by parrt** [comment]
hiya. looks like isCustomRegionElement() in ANTLRv4FoldingBuilder isn't available in 13.x. Can we use something for 13 *and* 14?

**Comment by jasonnn** [comment]
It looks like those custom folding methods are for things like netbeans style "<editor-fold...>" markup. I could probably just delete them?

**Comment by parrt** [comment]
That could work. I'm just trying to relearn my own codebase here. ugh

**Pull request closed without merging**
