### PR TITLE
Moved source files to their standard Gradle location 

### PR DESCRIPTION
**Pull request by bjansen**
@parrt I'm creating a PR for this because it basically moves every file to be consistent with the standard Gradle layout, and I want to make sure that it's okay with you.

Also, I'm not sure when/if `templates/org/antlr/intellij/plugin/gen/Java.stg` is used, so I'm not entirely sure I didn't break anything by moving it.

### CODE REVIEW

**Comment by parrt** [comment]
Wow. I can't find ref to Java.stg either. Hmm....seems we can delete. The `tokenTypeFile` template must be some old file from antlr itself?

As for dir name change, is there a reason beyond making it what gradle wants? If it works as-is and is simpler, maybe we should keep it?

**Comment by parrt** [comment]
actually, it looks like the adaptor got moved to new location so I'm ok with it. :) let's be consistent.

**Comment by bjansen** [comment]
I changed the directories because with the old structure, IntelliJ was confused by the fact that `resources` was both a resource root and a standard folder containing other resource roots:

```groovy
resources {
    srcDirs = ['resources', 'resources/icons', 'resources/templates', 'resources/liveTemplates', 'resources/colorSchemes']
}
```

As a result, most of its content was not shown in the Project view (at least on my machine):



I had to switch to the Project Files view to show  everything:



Now that there is a single resource root in `src/main/resources`, the problem is gone.

**Comment by parrt** [comment]
I noticed that and was freaked out too. thanks :)

**Pull request merged**
