### PR TITLE
Get rid of white fields around the icon.

### PR DESCRIPTION
**Pull request by Maccimo**
Get rid of white fields around the icon.

### CODE REVIEW

**Comment by parrt** [comment]
thanks!

**Comment by parrt** [comment]
Just for license cleanliness, can you add yourself to the [contributors list](https://github.com/antlr/intellij-plugin-v4/blob/master/contributors.txt)?

**Comment by Maccimo** [comment]
It seems that I should create another PR just to update contributors.txt since this one is already merged.
May be it will be easier if you update contributors list yourself?

Here is the line:

2015/07/30, maccimo, Maxim Degtyarev, mdegtyarev@gmail.com

**Comment by parrt** [comment]
hiya. it’s better to have your commit on it. another PR is fine.
Thanks!
Ter

**Comment by parrt** [comment]
Fixes #200

**Pull request merged**
